### ISSUE TITLE
HP Chormebook X2 - Intel.  Please post working modified script

### ISSUE THREAD

**Issue by nashi2000** [nolirium/aroc#15]
Can someone post the modified script which finanally worked on Chromebook X2.  That will avoid every single person trying to modify the scripts.
I see that some here have been able to root.  The current version of Nolirium script has some issue with Intel.  I was stuck at No space left...issue.  I modified th script and got passed that but encountered other errors.  I was going to try to do more modifications but I think since some people here already got it to work can you just give us.  The Test Script by NOlirium in another issue did not work for me.  ONly when I updated the ARchitecture code to force X86 did I get past the Space Error.
mmirg can you post your modified version until NOlirium get time to update his version?

**Comment by pinuke** [comment]
This is likely due to a failure in architecture detection. I'm currently looking into it.

**Comment by pinuke** [comment]
#17

**Comment by nashi2000** [comment]
Thank you so so so much.....smartguy for getting this fixed....I'm now rooted...
Thank you for posting your fix....I was able to run it ....
Thank you Nolirium for these scripts...  Now these work on Intel and ARM by Samrtguy196 fix.....

HP X2 ...ROOTED.....
