### ISSUE TITLE
ERROR: No running Android system found. Unable to patch sepolicy.

### ISSUE THREAD

**Issue by BruhDudeWew** [nolirium/aroc#33]
So when I run the combined script on ChromeOS v83, it shows the above error after installed busybox. Any fix?

**Comment by khanhtranngoccva** [comment]
It won't work with v77+. Make sure your Chromebook support Android apps. If you are running Chrome OS on a custom device, try this: github.com/gerriarob/arob. Make sure you have a x86_64 cpu and back up your data. You cannot unroot your device after that, or your software is broken.

**Comment by BruhDudeWew** [comment]
> It won't work with v77+. Make sure your Chromebook support Android apps. If you are running Chrome OS on a custom device, try this: github.com/gerriarob/arob. Make sure you have a x86_64 cpu and back up your data. You cannot unroot your device after that, or your software is broken.

Oh OK, no v83 support. That's why it failed. Well I does using Brunch framework on Custom device. I'll try that out. Thanks
