### ISSUE TITLE
ARC Stopped

### ISSUE THREAD

**Issue by bshouse** [nolirium/aroc#4]
I am not sure if it is just me or not, but after the latest update (on or around March 11, 2018), the script completes, but during the install there the ARC service dies repeatedly. After completion, no Android apps will run. I am going to return to the stock system image tonight. If time permits, I will attempt to root again and report.  Thank you for all your support. This script is a huge time saver.

**Comment by bshouse** [comment]
FYI: The restore fixed the problem with apps starting. I will try to root again and capture any relevant log messages.

**Comment by nolirium** [comment]
Might have been a space error copying the files, as it turns out that the stock image has gotten larger lately. I've updated the script to use a sparse file with max size 2GB so any space errors should hopefully be resolved now. If this hasn't solved your issue, feel free to post back.

**Comment by bshouse** [comment]
That appears to have worked the magic. Thank you!
